AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Setting up IAM users for Serverless CatDetector workshop. That will be used
  for creating Serverless application on top of Amazon Services, including
  Amazon Rekognition and others.

Parameters:

  PASSWORD:
    Description: >
      Start password for a participant.
    Type: String
    NoEcho: true

Resources:

  ParticipantGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: serverless-cat-detector-cloudyna2017-participants
      Policies:
        - PolicyName: serverless-cat-detector-cloudyna2017-participant-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - rekognition:*
                  - dynamodb:*
                  - lambda:*
                  - xray:*
                  - cloudwatch:*
                  - logs:*
                  - iam:*
                  - apigateway:*
                  - execute-api:*

                  - sns:*
                  - tag:*
                  - kms:ListAliases
                  - cloudformation:DescribeStackResources
                Resource: "*"

  User001:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user001
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User002:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user002
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User003:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user003
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User004:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user004
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User005:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user005
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User006:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user006
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User007:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user007
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User008:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user008
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User009:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user009
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User010:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user010
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User011:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user011
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User012:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user012
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User013:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user013
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User014:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user014
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User015:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user015
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User016:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user016
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User017:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user017
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User018:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user018
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User019:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user019
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User020:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user020
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User021:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user021
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User022:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user022
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User023:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user023
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User024:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user024
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User025:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user025
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User026:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user026
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User027:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user027
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User028:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user028
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User029:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user029
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User030:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user030
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User031:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user031
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

  User032:
    Type: AWS::IAM::User
    Properties:
      UserName: serverless-cat-detector-user032
      LoginProfile:
        Password: !Ref PASSWORD
        PasswordResetRequired: true
      Groups:
        - !Ref ParticipantGroup

